spring:
    datasource:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:file:./db/youthCouncilDB;DB_CLOSE_DELAY=-1
        username: admin
        password: admin
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: HSQL
