spring:
    profiles:
        active: dev # options: dev, prod
    jpa:
        show-sql: true
        open-in-view: false
        defer-datasource-initialization: true
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            additional-exclude: WEB-INF/**
    thymeleaf:
        cache: false
    sql:
        init:
            mode: always
#            data-locations: classpath:data.sql  comment this out once we have a data.sql file
#            schema-locations: classpath:schema.sql
server:
    port: 8081
logging:
    level:
        #    web: debug
        be.kdg.youthcouncil: debug
#        root: debug
        sql: debug
